# Generated by Django 2.2.1 on 2019-05-06 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soccerplayers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Leg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leg', models.CharField(max_length=30)),
            ],
        ),
        migrations.RemoveField(
            model_name='teamposition',
            name='leg',
        ),
    ]
