# Generated by Django 2.2.1 on 2019-05-06 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soccerplayers', '0002_auto_20190506_0223'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='soccerplayer',
            name='strongest_foot',
        ),
        migrations.AddField(
            model_name='soccerplayer',
            name='strongest_foot',
            field=models.ManyToManyField(to='soccerplayers.Leg'),
        ),
    ]
