# Generated by Django 2.2.1 on 2019-05-06 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soccerplayers', '0003_auto_20190506_0225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soccerplayer',
            name='ratings',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
