# Generated by Django 2.2.1 on 2019-05-04 03:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_featured'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='pic_picture',
            new_name='profile_picture',
        ),
    ]
