# Generated by Django 2.2.1 on 2019-05-04 16:28

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_posttiny'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posttiny',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
    ]
